INSERT INTO quick_access (name, icon_code, category, redirect_url, is_icon)
VALUES ('Facebook', 'fa-brands fa-facebook', 'Social Media', 'https://www.facebook.com/', 1),
('X-Twitter', 'fa-brands fa-x-twitter', 'Social Media', 'https://x.com/', 1),
('Instagram', 'fa-brands fa-instagram', 'Social Media', 'https://www.instagram.com', 1),
('LinkedIn', 'fa-brands fa-linkedin', 'Social Media', 'https://www.linkedin.com', 1),
('GitHub', 'fa-brands fa-github', 'Development Tools', 'https://www.github.com', 1),
('Discord', 'fa-brands fa-discord', 'Social Media', 'https://discord.com', 1),
('YouTube', 'fa-brands fa-youtube', 'Social Media', 'https://www.youtube.com', 1),
('WordPress', 'fa-brands fa-wordpress', 'CMS', 'https://wordpress.org', 1),
('Slack', 'fa-brands fa-slack', 'Collaboration Tools', 'https://slack.com', 1),
('Figma', 'fa-brands fa-figma', 'Design Tools', 'https://www.figma.com', 1),
('Apple', 'fa-brands fa-apple', 'Technology', 'https://www.apple.com', 1),
('Google', 'fa-brands fa-google', 'Technology', 'https://www.google.com', 1),
('Stripe', 'fa-brands fa-stripe', 'Payments', 'https://stripe.com', 1),
('Algolia', 'fa-brands fa-algolia', 'Search', 'https://www.algolia.com', 1),
('Docker', 'fa-brands fa-docker', 'Development Tools', 'https://www.docker.com', 1),
('Windows', 'fa-brands fa-windows', 'Technology', 'https://www.microsoft.com/windows', 1),
('PayPal', 'fa-brands fa-paypal', 'Payments', 'https://www.paypal.com', 1),
('Stack Overflow', 'fa-brands fa-stack-overflow', 'Development Tools', 'https://stackoverflow.com', 1),
('Shopify', 'fa-brands fa-shopify', 'E-commerce', 'https://www.shopify.com', 1),
('WhatsApp', 'fa-brands fa-whatsapp', 'Messaging', 'https://www.whatsapp.com', 1),
('Telegram', 'fa-brands fa-telegram', 'Messaging', 'https://telegram.org', 1),
('Pinterest', 'fa-brands fa-pinterest', 'Social Media', 'https://www.pinterest.com', 1),
('Salesforce', 'fa-brands fa-salesforce', 'CRM', 'https://www.salesforce.com', 1),
('freeCodeCamp', 'fa-brands fa-free-code-camp', 'Education', 'https://www.freecodecamp.org', 1),
('SoundCloud', 'fa-brands fa-soundcloud', 'Music', 'https://www.soundcloud.com', 1),
('Google Play', 'fa-brands fa-google-play', 'App Store', 'https://play.google.com', 1),
('React', 'fa-brands fa-react', 'Development Tools', 'https://reactjs.org', 1),
('Java', 'fa-brands fa-java', 'Programming Language', 'https://www.java.com', 1),
('Python', 'fa-brands fa-python', 'Programming Language', 'https://www.python.org', 1),
('Skype', 'fa-brands fa-skype', 'Messaging', 'https://www.skype.com', 1),
('Node.js', 'fa-brands fa-node', 'Development Tools', 'https://nodejs.org', 1),
('Amazon', 'fa-brands fa-amazon', 'E-commerce', 'https://www.amazon.com', 1),
('GitLab', 'fa-brands fa-gitlab', 'Development Tools', 'https://gitlab.com', 1),
('Spotify', 'fa-brands fa-spotify', 'Music', 'https://www.spotify.com', 1),
('Facebook Messenger', 'fa-brands fa-facebook-messenger', 'Messaging', 'https://www.messenger.com', 1),
('Microsoft', 'fa-brands fa-microsoft', 'Technology', 'https://www.microsoft.com', 1),
('Atlassian', 'fa-brands fa-atlassian', 'Development Tools', 'https://www.atlassian.com', 1),
('PlayStation', 'fa-brands fa-playstation', 'Gaming', 'https://www.playstation.com', 1),
('Swift', 'fa-brands fa-swift', 'Programming Language', 'https://swift.org', 1),
('Steam', 'fa-brands fa-steam', 'Gaming', 'https://store.steampowered.com', 1),
('Upwork', 'fa-brands fa-square-upwork', 'Freelancing', 'https://www.upwork.com', 1),
('Snapchat', 'fa-brands fa-snapchat', 'Social Media', 'https://www.snapchat.com', 1),
('Safari', 'fa-brands fa-safari', 'Web Browser', 'https://www.apple.com/safari', 1),
('Red Hat', 'fa-brands fa-redhat', 'Technology', 'https://www.redhat.com', 1),
('Raspberry Pi', 'fa-brands fa-raspberry-pi', 'Technology', 'https://www.raspberrypi.org', 1),
('PHP', 'fa-brands fa-php', 'Programming Language', 'https://www.php.net', 1),
('npm', 'fa-brands fa-npm', 'Development Tools', 'https://www.npmjs.com', 1),
('JSFiddle', 'fa-brands fa-jsfiddle', 'Development Tools', 'https://jsfiddle.net', 1),
('JavaScript', 'fa-brands fa-js', 'Programming Language', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', 1),
('Jira', 'fa-brands fa-jira', 'Project Management', 'https://www.atlassian.com/software/jira', 1),
('Jenkins', 'fa-brands fa-jenkins', 'Development Tools', 'https://www.jenkins.io', 1),
('iTunes', 'fa-brands fa-itunes', 'Music', 'https://www.apple.com/itunes', 1),
('HubSpot', 'fa-brands fa-hubspot', 'CRM', 'https://www.hubspot.com', 1),
('Google Drive', 'fa-brands fa-google-drive', 'Storage', 'https://www.google.com/drive', 1),
('Git', 'fa-brands fa-git', 'Development Tools', 'https://git-scm.com', 1),
('Font Awesome', 'fa-brands fa-font-awesome', 'Design Tools', 'https://fontawesome.com', 1),
('Flutter', 'fa-brands fa-flutter', 'Development Tools', 'https://flutter.dev', 1),
('Firefox', 'fa-brands fa-firefox-browser', 'Web Browser', 'https://www.mozilla.org/firefox', 1),
('Microsoft Edge', 'fa-brands fa-edge', 'Web Browser', 'https://www.microsoft.com/edge', 1),
('eBay', 'fa-brands fa-ebay', 'E-commerce', 'https://www.ebay.com', 1),
('DigitalOcean', 'fa-brands fa-digital-ocean', 'Cloud Hosting', 'https://www.digitalocean.com', 1),
('Dev.to', 'fa-brands fa-dev', 'Community', 'https://dev.to', 1),
('Google Chrome', 'fa-brands fa-chrome', 'Web Browser', 'https://www.google.com/chrome', 1),
('Brave', 'fa-brands fa-brave', 'Web Browser', 'https://brave.com', 1),
('Bootstrap', 'fa-brands fa-bootstrap', 'Development Tools', 'https://getbootstrap.com', 1),
('Blogger', 'fa-brands fa-blogger', 'CMS', 'https://www.blogger.com', 1),
('AWS', 'fa-brands fa-aws', 'Cloud Hosting', 'https://aws.amazon.com', 1),
('Audible', 'fa-brands fa-audible', 'Books', 'https://www.audible.com', 1),
('Angular', 'fa-brands fa-angular', 'Development Tools', 'https://angular.io', 1),
('Medium', 'fa-brands fa-medium', 'CMS', 'https://medium.com', 1),
('Trello', 'fa-brands fa-trello', 'Project Management', 'https://trello.com', 1),
('Adobe', 'placeholder-icon', 'Design Tools', 'https://www.adobe.com', 0),
('Bitbucket', 'fa-brands fa-bitbucket', 'Development Tools', 'https://bitbucket.org', 1),
('Dribbble', 'fa-brands fa-dribbble', 'Design Tools', 'https://dribbble.com', 1),
('Behance', 'fa-brands fa-behance', 'Design Tools', 'https://www.behance.net', 1),
('Kaggle', 'fa-brands fa-kaggle', 'Data Science', 'https://www.kaggle.com', 1),
('Quora', 'fa-brands fa-quora', 'Community', 'https://www.quora.com', 1),
('Zoho CRM', 'placeholder-icon', 'CRM', 'https://www.zoho.com/crm', 0),
('Pipedrive', 'placeholder-icon', 'CRM', 'https://www.pipedrive.com', 0),
('Freshsales', 'placeholder-icon', 'CRM', 'https://www.freshworks.com/crm', 0),
('SugarCRM', 'placeholder-icon', 'CRM', 'https://www.sugarcrm.com', 0),
('Microsoft Dynamics 365', 'fa-brands fa-microsoft', 'CRM', 'https://dynamics.microsoft.com', 1),
('Monday.com', 'placeholder-icon', 'CRM', 'https://monday.com', 0),
('Nimble', 'placeholder-icon', 'CRM', 'https://www.nimble.com', 0),
('ActiveCampaign', 'placeholder-icon', 'CRM', 'https://www.activecampaign.com', 0);
			